#pragma once

#include "NativeGameplayTags.h"

namespace AlsViewModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsLocomotionModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace AlsRotationModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace AlsStanceTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace AlsGaitTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace AlsOverlayModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(M4)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}

namespace AlsLocomotionActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
}

namespace AlsGroundedEntryModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FromRoll)
}

namespace EnemyTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy);
	namespace Alien
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red);
	}
	namespace Baloon
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(A);
	}
	namespace Bot
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Net);
	}
	namespace Computer
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PossessedPink);
	}
	namespace File
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CabinetFolder);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Guy);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop);
	}
	namespace Fish
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blob);
	}
	namespace Folder
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Manila);
	}
	namespace Furry
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Claw);
	}
	namespace Germ
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red);
	}
	namespace Ghost
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArmourGreen);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BloodyMouth);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BlueLegged);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boolean);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Camera);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cat);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chimney);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CreepyCute);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dark);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Encrypt);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileBlack);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FleshLegged);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Furry);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FurryBig);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FurryBlue);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GenericGrey);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GenericGreyDark);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GenericMetal);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Geometric);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GlobRed);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GloopyBlue);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GoardRed);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gooey);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GreenFish);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GreenFlesh);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GreenTeeth);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GunMetalRound);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HelmetGreen);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hex);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ink);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Integer);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Liquid);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Loop);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ManyEyedPink);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MechbodyRound);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MechaClaw);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MetalFleshRed);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MohSideTeeth);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monitor);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Newspaper);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nugget);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlantBig);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlantCute);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pointer);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PolygonGreen);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Program);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RhinoBw);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RoboBlue);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RoboGreen);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rocket);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RootRed);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScreenRed);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slimy);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpookyCute);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TentacleBeige);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Termite);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThreadBlue);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TongueSilver);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tumor);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TVHeadGrey);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TVLeg);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unicode);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Wire);
	}
	namespace Golden
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Possessed);
	}
	namespace Golem
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(A);
	}
	namespace Gooey
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(A);
	}
	namespace Gremlin
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green);
	}
	namespace Guy
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CuteYellow);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LittleElectric);
	}
	namespace Mine
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Code);
	}
	namespace Mouth
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Squiggly);
	}
	namespace Monster
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Big);
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heart);
	}
	namespace Smoke
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dark);
	}
	namespace Spiral
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green);
	}
	namespace Teeth
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Side);
	}
	namespace Wire
	{
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green);
	}
}

namespace FoodEffectTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_1)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_2)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_3)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_4)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_5)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_6)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_7)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_8)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_9)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_10)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_11)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_12)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_13)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_14)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_15)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_16)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_17)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_18)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_19)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_20)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_21)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_22)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_23)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_24)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_25)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_26)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_27)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_28)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_29)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_30)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_31)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_32)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_33)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_34)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_35)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_36)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_37)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_38)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_39)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_40)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_41)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_42)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_43)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_44)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_45)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_46)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_47)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_48)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_49)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_50)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_51)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_52)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_53)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_54)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_55)
}

namespace ClothesEffectTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AlphabetCoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ByteVest)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(JanitorOveralls)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WasherOveralls)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CalculatorGoggles)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GladiatorOutfit)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PorcupineCoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ForcefieldCoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BugZapperCoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimmonSweatpants)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RebootVest)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NullAndVoidHat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagneticVest)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AmmoBeltVest)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MasterMinMooMooSlippers)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BounceHouseSuit)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SheriffOutfit)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ManillaOxfordAndSlacks)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HoareSweaterVest)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NuttySpectacles)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BugHunterUniform)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SniperFocusOnLongRange)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boxer)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AdminPolo)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PorcelainCannon)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CarlOvercoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DebsFootballPads)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimonSweater)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_29)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LaoEddiesNightRobe)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoonDoggies)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Garbage)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PDEnergizerBattery)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DesperadoPoncho)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeliverySpandex)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WW2Uniform)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GreenhouseOutfit)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeartShapedSweater)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CableRepairOutfit)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NetworkSpecialist)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TroubleshooterJacket)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HotSwapPatch)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChefsApron)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MiddleAgedCyborgSamuraiTortoiseShell)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RastaRobe)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UndertakersCloak)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TranquilBlouse)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AntiGlitchHarness)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KnuthsOvercoat)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VcarSweatShirt)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AnandsTurtleneck)
		ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamerGear)
}
